---
- name: Test simple command
  hosts: all
  gather_facts: no
  tasks:
    - name: Echo Hello World
      ansible.builtin.shell: echo "Hello World"
      register: output

    - name: Print output
      ansible.builtin.debug:
        var: output.stdout
