---
- name: List Proxmox container templates
  hosts: all
  gather_facts: no
  tasks:
    - name: Get list of CTs marked as templates and write to a file
      shell: pvesh get /nodes/ens10pxcv/lxc --output-format=json | jq '.[] | select(.template == 1)' > /var/www/html/vmManagement/scripts/templates.json
      args:
        executable: /bin/bash
      become: yes # Utilisez cette option si nécessaire pour les permissions d'écriture
