# remove_lxc.yml
---
- name: Stop and Remove LXC containers in Proxmox hosts
  hosts: all
  vars:
    # Uncomment the following line to enable loading from the configuration file
    # remove_containers_file: "/var/www/html/vmManagement/scripts/remove_containers_config.yml"

  tasks:
    - name: 'Generate VMIDs to Stop and Remove'
      set_fact:
        vmids_to_remove: "{{ range(param_start_vmid|int, param_end_vmid|int + 1) |list }}"

    - name: 'Stop LXC Containers'
      command: >
        pct stop {{ item }}
      ignore_errors: yes
      with_items: "{{ vmids_to_remove }}"

    - name: 'Remove LXC Containers'
      command: >
        pct destroy {{ item }}
      ignore_errors: yes
      with_items: "{{ vmids_to_remove }}"
