# remove_containers.yml
---
- name: Remove LXC containers in Proxmox
  hosts: all
  vars:
    start_vmid: 105
    end_vmid: 106  # ajustez la fin de la plage selon vos besoins

  tasks:
    - name: 'Generate VMIDs to Remove'
      set_fact:
        vmids_to_remove: "{{ range(start_vmid, end_vmid + 1)|list }}"

    - name: 'Remove LXC Containers'
      command: >
        pct destroy {{ item }}
      delegate_to: 10.10.48.9
      ignore_errors: yes
      with_items: "{{ vmids_to_remove }}"
