# stop_containers.yml
---
- name: Stop LXC containers in Proxmox
  hosts: all
  vars:
    # Uncomment the following line to enable loading from the configuration file
    # stop_containers_file: "stop_containers_config.yml"

  tasks:
    # Uncomment the following task to enable loading from the configuration file
    # - name: 'Load Stop Containers Configuration'
    #   include_vars:
    #     file: "{{ stop_containers_file }}"
    #     name: stop_containers_config

    - name: 'Generate VMIDs to Stop'
      set_fact:
        # Modify this line to use parameters from the command line
        vmids_to_stop: "{{ range(param_start_vmid|int, param_end_vmid|int + 1)|list }}"

    - name: 'Stop LXC Containers'
      command: >
        pct stop {{ item }}
      ignore_errors: yes
      with_items: "{{ vmids_to_stop }}"
